name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*.lean'
      - 'lean-toolchain'
      - 'lakefile.toml'
      - 'lake-manifest.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.lean'
      - 'lean-toolchain'
      - 'lakefile.toml'
      - 'lake-manifest.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Lean and get mathlib cache
        uses: leanprover/lean-action@50fcf42d2e460296f1a34b402e990d1b24f8b596 # v1.6.0
        with:
          auto-config: false
          use-github-cache: false
          use-mathlib-cache: true

      - name: Build
        run: ~/.elan/bin/lake build OrdinalAnalysis
